apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: rootca-issuer
  namespace: cert-manager
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ca-issuer
  namespace: cert-manager
spec:
  secretName: ca-key-pair
  commonName: "k8-root-ca"
  dnsNames:
#  - nginx.gclab.cz
  - pvkbmgr01.gclab.cz
  - pvkbwkr01.gclab.cz
  - pvkbwkr02.gclab.cz
  - pvkbwkr03.gclab.cz
#  - pvkbboard01.gclab.cz
  isCA: true
  issuerRef:
    name: rootca-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: ca-issuer
  namespace: cert-manager
spec:
  ca:
    secretName: ca-key-pair

